### ISSUE TITLE
pgxmock doesn't support scanning nullables

### ISSUE THREAD

**Issue by OiCMudkips** [pashagolub/pgxmock#40]
**Describe the bug**
SQL column values can be `null`. `pgx/v4` supports this by having custom nullable structs, or scanning into pointers: https://pkg.go.dev/github.com/jackc/pgx#hdr-Null_Mapping. `pgxmock` can't test code that has to read and handle nulls because it does a [strict type comparison](https://github.com/pashagolub/pgxmock/blob/master/rows.go#L83).

**To Reproduce**
Here's a [sample repo](https://github.com/OiCMudkips/pgxmock-nullable-columns-bug) showing the issue, just clone and run `make test` to get this error:
```
--- FAIL: TestReadFromDatabase (0.00s)
    main_test.go:31: error: Destination kind 'ptr' not supported for value kind 'int' of column 'null_column'
FAIL
exit status 1
FAIL    github.com/OiCMudkips/pgxmockNullables  0.158s
```

**Expected behavior**
I would expect the test to not fail.

**Screenshots**
IMO N/A

**Additional context**
I will work on a PR to fix this this weekend, but initial guidance would be appreciated!

**Comment by OiCMudkips** [comment]
Wait I think I'm doing something wrong, let me look at this more.

**Comment by aaranmcguire** [comment]
Did you look at fixing this, as I think this is still an issue.

**Comment by pashagolub** [comment]
@aaranmcguire show us your code and we will try to investigate together

**Comment by aaranmcguire** [comment]
Thanks @pashagolub. I think I understand the issue again. It's wanting the exact type when doing the add row. So `AddRow( nil)` will work correctly, Providing a pointer of the same type to `AddRow()` will also allow the test to pass.

This again is unlike go-sqlmock making it more work to switch over. Do you have any thoughts on how to make it easier to swap over so types are more easily converted like PGX does?

**Comment by aaranmcguire** [comment]
With [DATA-DOG/go-sqlmock](https://github.com/DATA-DOG/go-sqlmock) you're able to `AddRow()` and it won't mind the type conversion when running `Scan()`. See below of what I would expect to work.

```go
	mock.ExpectQuery("SELECT .+ FROM test WHERE .+").
		WithArgs(1).
		WillReturnRows(db.NewRows(
			[]string{"id", "value"}).
			AddRow(uint64(1), "hello"),
		)
	rows := mock.QueryRow(context.Background(), "SELECT id, value FROM test WHERE id = $1", 1)

	var id uint64
	var value *string
	err = rows.Scan(&id, &value)
	if err != nil {
		t.Error(err)
	}
```

In your mock software you require the exact match, so you have to modify it to:

```diff
 
+       mockedValue := "hello"
        mock.ExpectQuery("SELECT .+ FROM test WHERE .+").
                WithArgs(1).
                WillReturnRows(db.NewRows(
                        []string{"id", "value"}).
-                       AddRow(uint64(1), "hello"),
+                       AddRow(uint64(1), &mockedValue),
                )
        rows := mock.QueryRow(context.Background(), "SELECT id, value FROM test WHERE id = $1", 1)

```

Which makes it harder to migrate from go-sqlmock, and doesn't **seem** to match exactly what pgx does as it coverts using this function: https://github.com/jackc/pgx/blob/master/values.go#L27

go-sqlmock also converts during `AddRow` into something the database would give too, so that on Scan it sees what a database may give: https://github.com/DATA-DOG/go-sqlmock/blob/master/rows.go#L173-L176

While I could update all the code to give the exact types, it's a bit of a pain, and makes it harder for others to convert over to pgx.

**Comment by pashagolub** [comment]
Thanks for the detailed explanation. I'll try to take a look. 

Of course, PRs are more than welcome!
