### ISSUE TITLE
pgpool.Acquire() method

### ISSUE THREAD

**Issue by danisorto** [pashagolub/pgxmock#42]
Hi, When the `pgpool.Adquire()` will be implemented?

This is the current code
``` go
func (p *pgxmockPool) Acquire(ctx context.Context) (*pgxpool.Conn, error) {
	return nil, errors.New("pgpool.Acquire() method is not implemented")
}
```

I need that method to test pg pool connections.

**Comment by pashagolub** [comment]
Hi, thanks for the question.

Probably never. Since the `Acquire` returns **the real** `*pgxpool.Conn` and not the interface.

If @jackc will change the signature in the next major, then it's possible.

I know the pain, I have some places with `Acquire` that I need to test on a real connection. Another approach would be to use https://github.com/jackc/pgmock and to implement own proxy
